# generated by datamodel-codegen:
#   filename:  common.schema.json
#   timestamp: 2026-10-07T04:41:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class CommonEnums(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Shared enums and small helpers used across other schemas.",
            title="CommonEnums",
        ),
    ]


class SystemName(str, Enum):
    """
    Target execution system for a Script/ScriptAction.
    """

    python = "python"
    adb = "adb"
    kvm = "kvm"
    none = "none"


class RunStatus(str, Enum):
    """
    Status reported by ScriptEngine for a running or finished action/script. The first four are ScriptExecutionState values. The last three come from ScriptExecutionStatusDetail: script_executor.py calls script_logger.get_action_log().set_status(status_detail), which writes the detail into this same field, so a terminated run's node reports why it stopped rather than a bare FAILURE. Readers should treat every value except RUNNING and SUCCESS as a failure-like terminal state.
    """

    running = "RUNNING"
    success = "SUCCESS"
    failure = "FAILURE"
    error = "ERROR"
    timed_out = "TIMED_OUT"
    max_attempts = "MAX_ATTEMPTS"
    cancelled = "CANCELLED"


class QueueStatus(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Status used in Script-Engine-Controller queue files (running_scripts/completed_scripts).",
            examples=[
                "pending",
                "started",
                "SUCCESS",
                "FAILURE",
                "ERROR",
                "completed",
                "waiting",
            ],
        ),
    ]


class FileType(str, Enum):
    """
    Type of a ScriptActionLog artifact file.
    """

    text = "text"
    image = "image"
    video = "video"
    directory = "directory"


class ScriptModePropEnum(str, Enum):
    train = "train"
    test = "test"
    prod = "prod"


class EditorStatusEnum(str, Enum):
    dirty = "dirty"
    clean = "clean"
    error = "error"


class FilePair1(BaseModel):
    """
    ScriptActionLog file reference pair (file_type + file_path). Empty object {} means no file is attached.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    file_type: FileType
    file_path: str


class FilePair(RootModel[FilePair1 | dict[str, Any]]):
    root: Annotated[
        FilePair1 | dict[str, Any],
        Field(
            description="ScriptActionLog file reference pair (file_type + file_path). Empty object {} means no file is attached."
        ),
    ]
