# generated by datamodel-codegen:
#   filename:  event-status.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import common_schema


class CommandItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["command"]
    key: str
    value: str | float | bool | None
    status: common_schema.QueueStatus


class VariableItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["variable"]
    key: str
    value: Any
    status: common_schema.QueueStatus


class ScriptItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["script"]
    script_name: str
    status: common_schema.QueueStatus


class EventStatus(BaseModel):
    """
    Entry shape used in running_events.json and completed_events.json. Each event is a 'sequence' tree composed of commands, variables, scripts, and nested sequences.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    event_id: Annotated[str, Field(description="UUID assigned by the controller.")]
    type: Literal["sequence"]
    sequence_name: str
    status: common_schema.QueueStatus
    start_time: Annotated[
        str | None,
        Field(
            description="ISO-8601 string (e.g. 2026-04-29T06:00:00Z). May be absent on freshly-created entries."
        ),
    ] = None
    timeout: Annotated[
        str | None,
        Field(
            description="ISO-8601 timestamp at which the event will time out, OR a duration string. TODO: pin to one form."
        ),
    ] = None
    end_time_str: str | None = None
    sequence: list[SequenceItem]
    sequences: Annotated[
        dict[str, Any] | None,
        Field(
            description="Map of named sub-sequences referenced by 'script'/'sequence' items. TODO: confirm shape of values."
        ),
    ] = None


class NestedSequenceItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["sequence"]
    sequence_name: str
    sequence: list[SequenceItem]
    sequences: dict[str, Any] | None = None
    status: common_schema.QueueStatus


class SequenceItem(
    RootModel[CommandItem | VariableItem | ScriptItem | NestedSequenceItem]
):
    root: CommandItem | VariableItem | ScriptItem | NestedSequenceItem


EventStatus.model_rebuild()
NestedSequenceItem.model_rebuild()
