# generated by datamodel-codegen:
#   filename:  script-action-artifacts.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import common_schema


class Presence(str, Enum):
    """
    always = engine MUST emit; optional = MAY emit; never = engine MUST NOT emit (slot is empty {}).
    """

    always = "always"
    optional = "optional"
    never = "never"


class FileSlot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_type: common_schema.FileType
    presence: Annotated[
        Presence,
        Field(
            description="always = engine MUST emit; optional = MAY emit; never = engine MUST NOT emit (slot is empty {})."
        ),
    ]
    name_suffix: Annotated[
        str | None,
        Field(
            description="Conventional filename suffix appended after the `<counter>-<actionName>-<group>-` log header."
        ),
    ] = None
    description: str | None = None


class Presence1(str, Enum):
    always = "always"
    optional = "optional"


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    presence: Presence1
    enum: list[str] | None = None
    description: str | None = None


class ActionArtifactSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pre_file: FileSlot
    post_file: FileSlot
    supporting_files: list[FileSlot]
    attributes: Annotated[
        dict[str, Attributes] | None,
        Field(
            description="Keys this action is expected to set in ScriptActionLog.attributes."
        ),
    ] = None


class ScriptActionArtifactsSpec(BaseModel):
    """
    Declarative mapping from each ScriptAction.actionName to the predictable set of pre/post/supplementary files that ScriptEngine is expected to attach to its ScriptActionLog. script-studio uses this to drive the Action Details viewer; ScriptEngine should use this as a contract when authoring new actions. TODO: cross-validate against actual executor implementations and fail CI on drift.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[str | None, Field(alias="$schema")] = None
    field_todo: Annotated[str | None, Field(alias="_TODO")] = None
    version: int
    actions: dict[str, ActionArtifactSpec]
