# generated by datamodel-codegen:
#   filename:  script-action-artifacts.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any
