# generated by datamodel-codegen:
#   filename:  script-status.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field

from . import common_schema


class ScriptStatus(BaseModel):
    """
    Entry shape used in running_scripts.json and completed_scripts.json (Script-Engine-Controller queues, read by script-studio host-data service).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    script_id: Annotated[
        str, Field(description="UUID assigned when the script enters the queue.")
    ]
    script_name: Annotated[
        str | None,
        Field(
            description="Script name, or null for legacy/system entries that lacked a name."
        ),
    ]
    status: common_schema.QueueStatus
    script_duration: Annotated[
        str, Field(description='Format: `<H>h<M>m`, e.g. "0h30m".')
    ]
    start_time_str: Annotated[
        str | None,
        Field(description='UTC "YYYY-MM-DD HH:MM:SS" — null until the script starts.'),
    ] = None
    end_time_str: str | None = None
    log_level: str | None = None
    notification_level: str | None = None
    device_details: Annotated[
        dict[str, Any] | str | None,
        Field(
            description="Either a structured object or a legacy device-id string (e.g. 'avd:Small_Phone_API_34'), or null."
        ),
    ] = None
    system_script: bool | None = None
    args: Annotated[
        list[Any] | None,
        Field(
            description="Script constants/arguments. TODO: tighten once arg shape is finalized."
        ),
    ] = None
    parallel: bool | None = None
    script_log_folder: str | None = None
    show_details: Annotated[
        bool | None,
        Field(
            alias="showDetails",
            description="UI-only field added by script-studio. Should not be relied on server-side.",
        ),
    ] = None
