# generated by datamodel-codegen:
#   filename:  script-action.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ActionName(str, Enum):
    """
    Discriminator for the ScriptAction subtype.
    """

    joint_action = "jointAction"
    click_action = "clickAction"
    mouse_scroll_action = "mouseScrollAction"
    declare_scene = "declareScene"
    conditional_statement = "conditionalStatement"
    shell_script = "shellScript"
    log_action = "logAction"
    sleep_statement = "sleepStatement"
    variable_assignment = "variableAssignment"
    time_action = "timeAction"
    random_variable = "randomVariable"
    script_reference = "scriptReference"
    drag_location_source = "dragLocationSource"
    drag_location_target = "dragLocationTarget"
    detect_object = "detectObject"
    keyboard_action = "keyboardAction"
    search_pattern_start_action = "searchPatternStartAction"
    search_pattern_continue_action = "searchPatternContinueAction"
    search_pattern_end_action = "searchPatternEndAction"
    randomizer_action = "randomizerAction"
    json_file_action = "jsonFileAction"
    exception_action = "exceptionAction"
    navigate_action = "navigateAction"
    image_to_text_action = "ImageToTextAction"
    image_to_text_action_1 = "imageToTextAction"
    scale = "scale"
    send_message_action = "sendMessageAction"
    code_block = "codeBlock"
    for_loop_action = "forLoopAction"
    configuration_action = "configurationAction"
    adb_configuration_action = "ADBConfigurationAction"
    color_compare_action = "colorCompareAction"
    return_statement = "returnStatement"
    image_transformation_action = "imageTransformationAction"
    count_to_threshold_action = "countToThresholdAction"
    file_io_action = "fileIOAction"
    mask_merge_action = "maskMergeAction"
    mouse_move_action = "mouseMoveAction"
    mouse_interaction_action = "mouseInteractionAction"
    user_prompt_action = "userPromptAction"
    calendar_action = "calendarAction"
    user_secret_management_action = "userSecretManagementAction"
    interact_application_action = "interactApplicationAction"


class ScriptAction(BaseModel):
    """
    A single ScriptAction node as authored in script-studio and consumed by ScriptEngine. The shape of `actionData` is discriminated on `actionName`; per-subtype payloads are defined in script-action-data.schema.json.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    action_name: Annotated[
        ActionName,
        Field(
            alias="actionName",
            description="Discriminator for the ScriptAction subtype.",
        ),
    ]
    action_icon: Annotated[
        dict[str, Any] | str | None,
        Field(
            alias="actionIcon",
            description="UI-only: icon descriptor (one of imageIcon|symbolIcon|svgIcon|textIcon|customIcon|blankIcon|gridIcon). Image references are persisted as relative paths or null.",
        ),
    ] = None
    action_data: Annotated[
        dict[str, Any],
        Field(
            alias="actionData",
            description="Per-actionName payload. Structure is selected by the oneOf below using actionName as discriminator.",
        ),
    ]
    action_group: Annotated[int, Field(alias="actionGroup")]
    action_groups: Annotated[
        list[int] | None,
        Field(alias="actionGroups", description="Only used by jointAction."),
    ] = None
    action_version: Annotated[int, Field(alias="actionVersion")]
    action_version_code: Annotated[str, Field(alias="actionVersionCode")]
    action_label: Annotated[str, Field(alias="actionLabel")]
    action_row_row_index: Annotated[int, Field(alias="actionRowRowIndex")]
    action_row_action_index: Annotated[int, Field(alias="actionRowActionIndex")]
    visualizer_row_index: Annotated[int, Field(alias="visualizerRowIndex")]
    visualizer_action_index: Annotated[int, Field(alias="visualizerActionIndex")]
    visualizer_x: Annotated[float, Field(alias="visualizerX")]
    visualizer_y: Annotated[float, Field(alias="visualizerY")]
    child_groups: Annotated[
        list[dict[str, Any]],
        Field(
            alias="childGroups",
            description="ActionLink array; concrete shape varies by branchingBehavior.",
        ),
    ]
    parent_groups: Annotated[list[int], Field(alias="parentGroups")]
    displayables: list[dict[str, Any]]
    configurables: list[dict[str, Any]]
    linking_behaviors: Annotated[list[dict[str, Any]], Field(alias="linkingBehaviors")]
    selected: bool | None = None
    draggable: bool | None = None
    highlight: str | None = None
    help_tip_expanded: Annotated[bool | None, Field(alias="helpTipExpanded")] = None
