# generated by datamodel-codegen:
#   filename:  script-action-log.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import common_schema


class LogObjectType(str, Enum):
    action = "action"
    script = "script"


class TreeEntityType(str, Enum):
    node = "node"
    child = "child"


class ChildStub(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    script_counter: int
    log_object_type: LogObjectType
    tree_entity_type: Literal["child"]
    action_log_path: str


class ScriptActionLog(BaseModel):
    """
    Per-action log document written by ScriptEngine (action-log.json) and consumed by script-studio's log-tree viewer. Source of truth: ScriptEngine/common/logging/script_action_log.py::_flush.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    base_path: str
    action_log_path: str
    id: Annotated[str, Field(description="UUID for this action log entry.")]
    name: Annotated[str, Field(description="Format: `<actionName>-<actionGroup>`.")]
    target_system: common_schema.SystemName
    script_name: str | None = None
    script_log_folder: str | None = None
    script_counter: int
    log_object_type: LogObjectType
    tree_entity_type: TreeEntityType
    status: common_schema.RunStatus
    summary: str | None = None
    start_time: Annotated[str, Field(description="UTC `YYYY-MM-DD HH:MM:SS.ffffff`.")]
    elapsed: Annotated[
        float,
        Field(
            description="Seconds between start_time and the sync end (or now if still running)."
        ),
    ]
    async_elapsed: Annotated[
        float | None,
        Field(
            description="Seconds between start_time and serialisation time (always real-time)."
        ),
    ] = None
    pre_file: common_schema.FilePair
    post_file: common_schema.FilePair
    supporting_files: list[common_schema.FilePair]
    children: list[ChildStub]
    attributes: Annotated[
        dict[str, Any],
        Field(
            description="Action-specific attributes. Currently set for scriptReference and detectObject. See artifacts spec for known keys."
        ),
    ]
