# generated by datamodel-codegen:
#   filename:  script-action-data.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import common_schema


class ScriptActionData(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Per-subtype `actionData` payload schemas for every ScriptAction subtype. Mirrors the TypeScript ActionData union in script-studio's editor/interfaces/script-action-types.ts. On-disk representations differ from authoring-time types in two ways: (1) Blob/SafeUrl/ImageData fields are persisted as relative file-path strings (or null) — see ScriptImportExportUtils in script-studio; (2) historic scripts may carry legacy fields no longer authored, so each subtype keeps additionalProperties:true and a small `required` list.",
            title="ScriptActionData",
        ),
    ]


class ProgrammingLanguage(str, Enum):
    python = "python"


class BoundType(str, Enum):
    full_screen = "fullScreen"
    full_window = "fullWindow"
    custom_bounds = "customBounds"


class TargetContext(str, Enum):
    screen = "screen"
    search_area = "searchArea"
    detect_result = "detectResult"


class Point2D(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=2, min_length=2)]


class Rect2D(RootModel[list[Point2D]]):
    root: Annotated[list[Point2D], Field(max_length=2, min_length=2)]


class RGB(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=3, min_length=3)]


class ImageRef(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description="On-disk persisted image reference: relative path (string), embedded data, or null. Authoring-time Blob/ImageData is unloaded to a path before serialisation."
        ),
    ]


class CanvasShape1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    shape: Literal["circle"]
    shape_x: Annotated[float, Field(alias="shapeX")]
    shape_y: Annotated[float, Field(alias="shapeY")]
    radius: float
    fill_type: Annotated[Literal["fill"], Field(alias="fillType")]


class CanvasShape2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    shape: Literal["rectangle"]
    shape_x: Annotated[float, Field(alias="shapeX")]
    shape_y: Annotated[float, Field(alias="shapeY")]
    width: float
    height: float
    fill_type: Annotated[Literal["fill"], Field(alias="fillType")]


class CanvasShape(RootModel[CanvasShape1 | CanvasShape2]):
    root: CanvasShape1 | CanvasShape2


class CanvasShapeRows(RootModel[list[list[CanvasShape]]]):
    root: list[list[CanvasShape]]


class DistributionType(str, Enum):
    uniform = "uniform"
    normal = "normal"


class RandomVariableTypeData(BaseModel):
    """
    Distribution sampling parameters. Newer fields (normalDist*/uniformDist*) coexist with legacy fields (min/max/mean/stddev/distType) on disk.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    distribution_type: Annotated[
        DistributionType | None, Field(alias="distributionType")
    ] = None
    normal_dist_min: Annotated[float | str | None, Field(alias="normalDistMin")] = None
    normal_dist_max: Annotated[float | str | None, Field(alias="normalDistMax")] = None
    normal_dist_mean: Annotated[
        float | str | None, Field(alias="normalDistMean")
    ] = None
    normal_dist_std_dev: Annotated[
        float | str | None, Field(alias="normalDistStdDev")
    ] = None
    uniform_dist_min: Annotated[
        float | str | None, Field(alias="uniformDistMin")
    ] = None
    uniform_dist_max: Annotated[
        float | str | None, Field(alias="uniformDistMax")
    ] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None


class DetectTypeImageMaskPair(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    detect_type: Annotated[str | None, Field(alias="detectType")] = None
    pair_index: Annotated[int | None, Field(alias="pairIndex")] = None
    img: ImageRef | None = None
    mask: ImageRef | None = None
    contained_area_mask: Annotated[
        ImageRef | None, Field(alias="containedAreaMask")
    ] = None
    icon: ImageRef | None = None
    center_point: Annotated[Point2D | None, Field(alias="centerPoint")] = None
    source_screen_width: Annotated[
        float | None, Field(alias="sourceScreenWidth")
    ] = None
    source_screen_height: Annotated[
        float | None, Field(alias="sourceScreenHeight")
    ] = None


class DetectTypePositiveExamplePair(BaseModel):
    """
    One capture: floating and/or fixed positive examples. Some legacy entries carry the bare DetectTypeImageMaskPair shape directly.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str | None = None
    floating_object: Annotated[
        DetectTypeImageMaskPair | None, Field(alias="floatingObject")
    ] = None
    fixed_object: Annotated[
        DetectTypeImageMaskPair | None, Field(alias="fixedObject")
    ] = None


class DetectorName(str, Enum):
    pixel_difference = "pixelDifference"
    logistic_classifier = "logisticClassifier"
    conv_net = "convNet"


class DetectorMode(str, Enum):
    training = "training"
    active = "active"
    inactive = "inactive"


class MatchMode(str, Enum):
    first_match = "firstMatch"
    best_match = "bestMatch"


class DetectActionType(str, Enum):
    floating_object = "floatingObject"
    fixed_object = "fixedObject"


class DetectTypeData(BaseModel):
    """
    Detector configuration shared by detectObject, click/drag/mouse-* actions, etc. Image fields persist as relative paths or null.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    icon: ImageRef | None = None
    detector_name: Annotated[DetectorName | None, Field(alias="detectorName")] = None
    include_contained_area_in_output: Annotated[
        bool | None, Field(alias="includeContainedAreaInOutput")
    ] = None
    exclude_matched_area_from_output: Annotated[
        bool | None, Field(alias="excludeMatchedAreaFromOutput")
    ] = None
    threshold: float | str | None = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    resuse_screenshot_between_actions: Annotated[
        bool | None, Field(alias="resuseScreenshotBetweenActions")
    ] = None
    use_color: Annotated[bool | None, Field(alias="useColor")] = None
    use_original_image_only: Annotated[
        bool | None, Field(alias="useOriginalImageOnly")
    ] = None
    use_image_rescaled_to_screen_only: Annotated[
        bool | None, Field(alias="useImageRescaledToScreenOnly")
    ] = None
    detector_mode: Annotated[DetectorMode | None, Field(alias="detectorMode")] = None
    src_img: Annotated[ImageRef | None, Field(alias="srcImg")] = None
    src_shape: Annotated[CanvasShapeRows | None, Field(alias="srcShape")] = None
    src_scale_factor: Annotated[float | None, Field(alias="srcScaleFactor")] = None
    positive_examples: Annotated[
        list[DetectTypePositiveExamplePair] | None, Field(alias="positiveExamples")
    ] = None
    negative_examples: Annotated[
        list[DetectTypeImageMaskPair] | None, Field(alias="negativeExamples")
    ] = None
    scene_location: Annotated[
        list[Point2D] | None, Field(alias="sceneLocation", max_length=2, min_length=2)
    ] = None
    mask_location: Annotated[
        list[Point2D] | None, Field(alias="maskLocation", max_length=2, min_length=2)
    ] = None
    match_mode: Annotated[MatchMode | None, Field(alias="matchMode")] = None
    detect_action_type: Annotated[
        DetectActionType | None, Field(alias="detectActionType")
    ] = None
    skip_detection: Annotated[bool | None, Field(alias="skipDetection")] = None


class MouseButton(str, Enum):
    left = "left"
    right = "right"


class ClickActionData(DetectTypeData, RandomVariableTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    target_context: Annotated[TargetContext | None, Field(alias="targetContext")] = None
    point_list: Annotated[list[Point2D] | None, Field(alias="pointList")] = None
    icon: ImageRef | None = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    click_count: Annotated[int | str | None, Field(alias="clickCount")] = None
    mouse_button: Annotated[MouseButton | None, Field(alias="mouseButton")] = None
    post_action_delay: Annotated[
        str | float | None, Field(alias="postActionDelay")
    ] = None


class MouseScrollActionData(DetectTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    target_context: Annotated[TargetContext | None, Field(alias="targetContext")] = None
    point_list: Annotated[list[Point2D] | None, Field(alias="pointList")] = None
    icon: ImageRef | None = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    scroll_distance: Annotated[float | str | None, Field(alias="scrollDistance")] = None


class DeclareSceneData(DetectTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    target_context: Annotated[TargetContext | None, Field(alias="targetContext")] = None
    location: Point2D | None = None
    search_area: Annotated[Rect2D | None, Field(alias="searchArea")] = None
    bound_type: Annotated[BoundType | None, Field(alias="boundType")] = None
    icon: ImageRef | None = None
    mask_location: Annotated[
        list[Point2D] | None, Field(alias="maskLocation", max_length=2, min_length=2)
    ] = None


class ConditionalStatementData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    condition: str
    condition_language: Annotated[
        ProgrammingLanguage | None, Field(alias="conditionLanguage")
    ] = None


class JointActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class ShellScriptActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    cwd: str | None = None
    shell_script: Annotated[str, Field(alias="shellScript")]
    await_script: Annotated[bool | None, Field(alias="awaitScript")] = None
    pipe_output_var_name: Annotated[str | None, Field(alias="pipeOutputVarName")] = None
    return_code_output_var_name: Annotated[
        str | None, Field(alias="returnCodeOutputVarName")
    ] = None
    open_in_new_window: Annotated[bool | None, Field(alias="openInNewWindow")] = None


class LogType(str, Enum):
    log_variable = "logVariable"
    log_image = "logImage"


class LogActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    log_type: Annotated[LogType | None, Field(alias="logType")] = None
    log_value: Annotated[str | None, Field(alias="logValue")] = None
    log_file: Annotated[str | None, Field(alias="logFile")] = None


class SleepStatementData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    input_expression: Annotated[
        str | float | None, Field(alias="inputExpression")
    ] = None


class InputParser(str, Enum):
    eval = "eval"
    jsonload = "jsonload"


class VariableAssignmentData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    expression_language: Annotated[
        ProgrammingLanguage | None, Field(alias="expressionLanguage")
    ] = None
    input_parser: Annotated[InputParser | None, Field(alias="inputParser")] = None
    set_if_null: Annotated[bool | None, Field(alias="setIfNull")] = None


class TimeActionType(str, Enum):
    get_current_date_time = "getCurrentDateTime"


class Timezone(str, Enum):
    local = "local"
    utc = "utc"


class TimeActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    time_action_type: Annotated[
        TimeActionType | None, Field(alias="timeActionType")
    ] = None
    timezone: Timezone | None = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None


class RandomVariableData(RandomVariableTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]


class ScriptAttribute(str, Enum):
    search_area_error_handler = "searchAreaErrorHandler"
    search_area_object_handler = "searchAreaObjectHandler"
    search_area_excluded = "searchAreaExcluded"


class BranchingBehavior(str, Enum):
    first_match = "firstMatch"
    attempt_all_branches = "attemptAllBranches"


class RunMode(str, Enum):
    run = "run"
    run_one = "runOne"
    run_to_failure = "runToFailure"


class ActionOrder(str, Enum):
    sequential = "sequential"
    random = "random"


class ScriptReferenceData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    script_name: Annotated[str, Field(alias="scriptName")]
    script_attributes: Annotated[
        list[ScriptAttribute] | None, Field(alias="scriptAttributes")
    ] = None
    branching_behavior: Annotated[
        BranchingBehavior | None, Field(alias="branchingBehavior")
    ] = None
    run_mode: Annotated[RunMode | None, Field(alias="runMode")] = None
    action_order: Annotated[ActionOrder | None, Field(alias="actionOrder")] = None
    script_max_action_attempts: Annotated[
        str | float | None, Field(alias="scriptMaxActionAttempts")
    ] = None
    on_out_of_action_attempts: Annotated[
        str | None, Field(alias="onOutOfActionAttempts")
    ] = None
    library_script: Annotated[bool | None, Field(alias="libraryScript")] = None
    post_action_delay: Annotated[
        str | float | None, Field(alias="postActionDelay")
    ] = None


class DragType(Enum):
    slow = "slow"
    fast = "fast"
    none_type_none = None


class DragLocationData(DetectTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    target_context: Annotated[TargetContext | None, Field(alias="targetContext")] = None
    point_list: Annotated[list[Point2D] | None, Field(alias="pointList")] = None
    icon: ImageRef | None = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    drag_type: Annotated[DragType | None, Field(alias="dragType")] = None
    post_action_delay: Annotated[
        str | float | None, Field(alias="postActionDelay")
    ] = None


class DetectObjectData(DetectTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    target_context: Annotated[TargetContext | None, Field(alias="targetContext")] = None
    search_area: Annotated[Rect2D | None, Field(alias="searchArea")] = None
    max_matches: Annotated[int | str | None, Field(alias="maxMatches")] = None
    height_scale: Annotated[str | float | None, Field(alias="heightScale")] = None
    width_scale: Annotated[str | float | None, Field(alias="widthScale")] = None


class KeyboardActionType(str, Enum):
    key_press = "keyPress"
    key_down = "keyDown"
    key_up = "keyUp"
    hotkey = "hotkey"


class KeyboardActionData(RandomVariableTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    keyboard_expression: Annotated[str | None, Field(alias="keyboardExpression")] = None
    keyboard_action_type: Annotated[
        KeyboardActionType | None, Field(alias="keyboardActionType")
    ] = None
    post_action_delay: Annotated[
        str | float | None, Field(alias="postActionDelay")
    ] = None


class SearchPatternStartActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    search_pattern_id: Annotated[str, Field(alias="searchPatternID")]
    search_patterns: Annotated[list[str] | None, Field(alias="searchPatterns")] = None
    search_pattern_probabilities: Annotated[
        list[float] | None, Field(alias="searchPatternProbabilities")
    ] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    draggable_area: Annotated[ImageRef | None, Field(alias="draggableArea")] = None
    grid_mode: Annotated[DetectorMode | None, Field(alias="gridMode")] = None


class SearchPatternContinueActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    search_pattern_id: Annotated[str, Field(alias="searchPatternID")]
    grid_mode: Annotated[DetectorMode | None, Field(alias="gridMode")] = None
    record_search_area_map: Annotated[
        bool | None, Field(alias="recordSearchAreaMap")
    ] = None


class SearchPatternEndActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    search_pattern_id: Annotated[str, Field(alias="searchPatternID")]
    grid_mode: Annotated[DetectorMode | None, Field(alias="gridMode")] = None
    generate_search_area_map: Annotated[
        bool | None, Field(alias="generateSearchAreaMap")
    ] = None


class RandomizerBehavior(str, Enum):
    randomizer = "randomizer"
    random_queue = "randomQueue"


class RandomizerActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    randomizer_behavior: Annotated[
        RandomizerBehavior | None, Field(alias="randomizerBehavior")
    ] = None
    preferences: str | None = None


class Mode(str, Enum):
    read = "read"
    write = "write"


class JSONFileActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    mode: Mode | None = None
    file_name: Annotated[str | None, Field(alias="fileName")] = None
    var_name: Annotated[str | None, Field(alias="varName")] = None
    file_contents: Annotated[str | None, Field(alias="fileContents")] = None


class ExceptionActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    exception_message: Annotated[str | None, Field(alias="exceptionMessage")] = None
    take_screenshot: Annotated[bool | None, Field(alias="takeScreenshot")] = None
    exception_id: Annotated[str | None, Field(alias="exceptionID")] = None
    exit_program: Annotated[bool | None, Field(alias="exitProgram")] = None


class NavigateActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    max_navigate_attempts: Annotated[
        int | str | None, Field(alias="maxNavigateAttempts")
    ] = None


class ConversionEngine(str, Enum):
    tesseract_ocr = "tesseractOCR"
    easy_ocr = "easyOCR"


class TargetType(str, Enum):
    character = "character"
    word = "word"
    sentence = "sentence"
    page = "page"
    raw_line = "rawLine"


class RunMode1(str, Enum):
    normal = "normal"
    debug = "debug"


class Blur(str, Enum):
    false = "false"
    median_blur = "medianBlur"
    gaussian_blur = "gaussianBlur"
    bilateral_filter = "bilateralFilter"


class Binarize(str, Enum):
    false = "false"
    regular = "regular"
    adaptive = "adaptive"


class ImageToTextActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    target_context: Annotated[TargetContext | None, Field(alias="targetContext")] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    conversion_engine: Annotated[
        ConversionEngine | None, Field(alias="conversionEngine")
    ] = None
    character_white_list: Annotated[
        str | None, Field(alias="characterWhiteList")
    ] = None
    target_type: Annotated[TargetType | None, Field(alias="targetType")] = None
    run_mode: Annotated[RunMode1 | None, Field(alias="runMode")] = None
    increase_contrast: Annotated[bool | None, Field(alias="increaseContrast")] = None
    invert_colors: Annotated[bool | None, Field(alias="invertColors")] = None
    blur: Blur | None = None
    binarize: Binarize | None = None
    make_border: Annotated[bool | None, Field(alias="makeBorder")] = None


class DataLabels(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    height_labels: Annotated[list[float] | None, Field(alias="heightLabels")] = None
    width_labels: Annotated[list[float] | None, Field(alias="widthLabels")] = None


class ScaleTarget(str, Enum):
    height = "height"
    width = "width"


class ScaleData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    data_rows: Annotated[list[list[float]] | None, Field(alias="dataRows")] = None
    source_width: Annotated[float | None, Field(alias="sourceWidth")] = None
    source_height: Annotated[float | None, Field(alias="sourceHeight")] = None
    data_labels: Annotated[DataLabels | None, Field(alias="dataLabels")] = None
    x_coefficient: Annotated[float | None, Field(alias="xCoefficient")] = None
    use_x_coefficient: Annotated[bool | None, Field(alias="useXCoefficient")] = None
    y_coefficient: Annotated[float | None, Field(alias="yCoefficient")] = None
    use_y_coefficient: Annotated[bool | None, Field(alias="useYCoefficient")] = None
    constant_term: Annotated[float | None, Field(alias="constantTerm")] = None
    scale_target: Annotated[ScaleTarget | None, Field(alias="scaleTarget")] = None


class MessagingProvider(str, Enum):
    viber = "viber"
    email = "email"


class MessageType(str, Enum):
    image = "image"
    text = "text"


class SendMessageActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[
        common_schema.SystemName | None, Field(alias="targetSystem")
    ] = None
    subject: str | None = None
    messaging_provider: Annotated[
        MessagingProvider | None, Field(alias="messagingProvider")
    ] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    message_type: Annotated[MessageType | None, Field(alias="messageType")] = None
    messaging_channel_name: Annotated[
        str | None, Field(alias="messagingChannelName")
    ] = None


class CodeBlockActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    code_block: Annotated[str | None, Field(alias="codeBlock")] = None
    interpreter: ProgrammingLanguage | None = None
    expanded_visualization: Annotated[
        bool | None, Field(alias="expandedVisualization")
    ] = None
    expanded_width_cols: Annotated[
        float | None, Field(alias="expandedWidthCols")
    ] = None
    expanded_height_rows: Annotated[
        float | None, Field(alias="expandedHeightRows")
    ] = None


class OperatorType(str, Enum):
    start_loop = "startLoop"
    end_loop = "endLoop"


class ForLoopActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    for_variables: Annotated[str | None, Field(alias="forVariables")] = None
    in_variables: Annotated[str | None, Field(alias="inVariables")] = None
    operator_type: Annotated[OperatorType | None, Field(alias="operatorType")] = None


class ConfigurationActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    configuration_type: Annotated[str, Field(alias="configurationType")]


class EmulatorType(str, Enum):
    bluestacks = "bluestacks"


class ADBConfigurationData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    configuration_type: Annotated[Literal["adb"], Field(alias="configurationType")]
    adb_path: Annotated[str | None, Field(alias="adbPath")] = None
    emulator_type: Annotated[EmulatorType | None, Field(alias="emulatorType")] = None
    device_name: Annotated[str | None, Field(alias="deviceName")] = None
    window_name: Annotated[str | None, Field(alias="windowName")] = None
    adb_port: Annotated[str | float | None, Field(alias="adbPort")] = None
    emulator_path: Annotated[str | None, Field(alias="emulatorPath")] = None
    auto_detect_adb_port: Annotated[
        bool | None, Field(alias="autoDetectAdbPort")
    ] = None
    target_system: Annotated[Literal["adb"], Field(alias="targetSystem")] = "adb"


class CompareMode(str, Enum):
    mean = "mean"
    mode = "mode"


class ColorCompareActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[
        common_schema.SystemName | None, Field(alias="targetSystem")
    ] = None
    icon: ImageRef | None = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    threshold: float | str | None = None
    reference_color: Annotated[RGB | None, Field(alias="referenceColor")] = None
    reference_image: Annotated[str | None, Field(alias="referenceImage")] = None
    compare_mode: Annotated[CompareMode | None, Field(alias="compareMode")] = None
    source_detect_type_data: Annotated[
        DetectTypeData | None, Field(alias="sourceDetectTypeData")
    ] = None


class ReturnStatementType(str, Enum):
    exit_iteration = "exitIteration"
    exit_script = "exitScript"
    exit_program = "exitProgram"


class ReturnStatus(str, Enum):
    success = "success"
    failure = "failure"


class ReturnStatementActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[
        common_schema.SystemName | None, Field(alias="targetSystem")
    ] = None
    return_statement_type: Annotated[
        ReturnStatementType | None, Field(alias="returnStatementType")
    ] = None
    return_status: Annotated[ReturnStatus | None, Field(alias="returnStatus")] = None


class TransformationType(str, Enum):
    blur = "blur"
    binarize = "binarize"
    antialias = "antialias"
    resize = "resize"
    erode = "erode"
    dilate = "dilate"
    convert_color = "convertColor"


class ConvertColorType(str, Enum):
    none = "none"
    bg_rto_gray_scale = "BGRtoGrayScale"
    invert = "invert"


class ImageTransformationActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    transformation_type: Annotated[
        TransformationType | None, Field(alias="transformationType")
    ] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    blur_type: Annotated[Blur | None, Field(alias="blurType")] = None
    blur_kernel_size: Annotated[
        float | str | None, Field(alias="blurKernelSize")
    ] = None
    binarize_type: Annotated[Binarize | None, Field(alias="binarizeType")] = None
    antialias_scale_factor: Annotated[
        float | str | None, Field(alias="antialiasScaleFactor")
    ] = None
    resize_scale_factor: Annotated[
        float | str | None, Field(alias="resizeScaleFactor")
    ] = None
    erode_kernel_size: Annotated[
        float | str | None, Field(alias="erodeKernelSize")
    ] = None
    erode_iterations: Annotated[
        float | str | None, Field(alias="erodeIterations")
    ] = None
    dilate_kernel_size: Annotated[
        float | str | None, Field(alias="dilateKernelSize")
    ] = None
    dilate_iterations: Annotated[
        float | str | None, Field(alias="dilateIterations")
    ] = None
    convert_color_type: Annotated[
        ConvertColorType | None, Field(alias="convertColorType")
    ] = None


class ThresholdType(str, Enum):
    counter = "counter"
    timer = "timer"


class CountToThresholdActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    counter_var_name: Annotated[str | None, Field(alias="counterVarName")] = None
    counter_threshold: Annotated[
        str | float | None, Field(alias="counterThreshold")
    ] = None
    increment_by: Annotated[str | float | None, Field(alias="incrementBy")] = None
    initial_value: Annotated[str | float | None, Field(alias="initialValue")] = None
    threshold_type: Annotated[ThresholdType | None, Field(alias="thresholdType")] = None
    counter_threshold_seconds: Annotated[
        str | float | None, Field(alias="counterThresholdSeconds")
    ] = None
    reset_counter_after_breached: Annotated[
        bool | None, Field(alias="resetCounterAfterBreached")
    ] = None


class FileActionType(str, Enum):
    w = "w"
    r = "r"
    wb = "wb"
    rb = "rb"
    a = "a"


class FileType(str, Enum):
    image = "image"
    text = "text"
    json = "json"


class FileIOActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    file_action_type: Annotated[
        FileActionType | None, Field(alias="fileActionType")
    ] = None
    file_type: Annotated[FileType | None, Field(alias="fileType")] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    file_path: Annotated[str | None, Field(alias="filePath")] = None
    async_: Annotated[bool | None, Field(alias="async")] = None


class JoinLeftAt(str, Enum):
    angle = "angle"
    top_left = "topLeft"
    top = "top"
    top_right = "topRight"
    right = "right"
    bottom_right = "bottomRight"
    bottom = "bottom"
    bottom_left = "bottomLeft"
    left = "left"


class LeftMaskPositioning(str, Enum):
    floating = "floating"
    fixed = "fixed"


class FillSpaceBetweenUsing(str, Enum):
    horizontal_overlap = "horizontalOverlap"
    vertical_overlap = "verticalOverlap"
    linear = "linear"


class FillAccordingToBoundariesOf(str, Enum):
    left_mask = "leftMask"
    right_mask = "rightMask"
    both = "both"


class MaskMergeActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    left_input_expression: Annotated[
        str | None, Field(alias="leftInputExpression")
    ] = None
    right_input_expression: Annotated[
        str | None, Field(alias="rightInputExpression")
    ] = None
    join_left_at: Annotated[JoinLeftAt | None, Field(alias="joinLeftAt")] = None
    join_left_angle: Annotated[str | float | None, Field(alias="joinLeftAngle")] = None
    join_right_at: Annotated[JoinLeftAt | None, Field(alias="joinRightAt")] = None
    join_right_angle: Annotated[
        str | float | None, Field(alias="joinRightAngle")
    ] = None
    left_mask_positioning: Annotated[
        LeftMaskPositioning | None, Field(alias="leftMaskPositioning")
    ] = None
    right_mask_positioning: Annotated[
        LeftMaskPositioning | None, Field(alias="rightMaskPositioning")
    ] = None
    include_left_mask: Annotated[bool | None, Field(alias="includeLeftMask")] = None
    include_right_mask: Annotated[bool | None, Field(alias="includeRightMask")] = None
    include_space_between: Annotated[
        bool | None, Field(alias="includeSpaceBetween")
    ] = None
    fill_space_between_using: Annotated[
        FillSpaceBetweenUsing | None, Field(alias="fillSpaceBetweenUsing")
    ] = None
    fill_according_to_boundaries_of: Annotated[
        FillAccordingToBoundariesOf | None, Field(alias="fillAccordingToBoundariesOf")
    ] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None


class MouseMoveActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[
        common_schema.SystemName | None, Field(alias="targetSystem")
    ] = None
    drag_mouse: Annotated[bool | None, Field(alias="dragMouse")] = None
    release_mouse_on_completion: Annotated[
        bool | None, Field(alias="releaseMouseOnCompletion")
    ] = None
    source_detect_type_data: Annotated[
        DetectTypeData | None, Field(alias="sourceDetectTypeData")
    ] = None
    target_detect_type_data: Annotated[
        DetectTypeData | None, Field(alias="targetDetectTypeData")
    ] = None
    source_point_list: Annotated[
        list[Point2D] | None, Field(alias="sourcePointList")
    ] = None
    target_point_list: Annotated[
        list[Point2D] | None, Field(alias="targetPointList")
    ] = None
    post_action_delay: Annotated[
        str | float | None, Field(alias="postActionDelay")
    ] = None


class MouseActionType(str, Enum):
    click = "click"
    mouse_down = "mouseDown"
    mouse_up = "mouseUp"
    scroll = "scroll"


class MouseInteractionActionData(RandomVariableTypeData):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    source_detect_type_data: Annotated[
        DetectTypeData | None, Field(alias="sourceDetectTypeData")
    ] = None
    source_point_list: Annotated[
        list[Point2D] | None, Field(alias="sourcePointList")
    ] = None
    click_count: Annotated[int | str | None, Field(alias="clickCount")] = None
    mouse_button: Annotated[MouseButton | None, Field(alias="mouseButton")] = None
    post_action_delay: Annotated[
        str | float | None, Field(alias="postActionDelay")
    ] = None
    scroll_distance: Annotated[float | str | None, Field(alias="scrollDistance")] = None
    mouse_action_type: Annotated[
        MouseActionType | None, Field(alias="mouseActionType")
    ] = None
    between_click_delay: Annotated[bool | None, Field(alias="betweenClickDelay")] = None
    random_variable_type_data: Annotated[
        RandomVariableTypeData | None, Field(alias="randomVariableTypeData")
    ] = None


class PromptType(str, Enum):
    text = "text"
    yesno = "yesno"
    okcancel = "okcancel"


class MessagingProvider1(str, Enum):
    viber = "viber"
    web = "web"


class UserPromptActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[
        common_schema.SystemName | None, Field(alias="targetSystem")
    ] = None
    prompt_message: Annotated[str | None, Field(alias="promptMessage")] = None
    prompt_type: Annotated[PromptType | None, Field(alias="promptType")] = None
    default_value: Annotated[str | None, Field(alias="defaultValue")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    messaging_provider: Annotated[
        MessagingProvider1 | None, Field(alias="messagingProvider")
    ] = None
    messaging_channel_name: Annotated[
        str | None, Field(alias="messagingChannelName")
    ] = None
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None


class CalendarActionType(str, Enum):
    create = "create"
    update = "update"
    delete = "delete"
    list = "list"


class CalendarActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    calendar_action_type: Annotated[
        CalendarActionType | None, Field(alias="calendarActionType")
    ] = None
    calendar_id: Annotated[str | None, Field(alias="calendarId")] = None
    event_title: Annotated[str | None, Field(alias="eventTitle")] = None
    event_description: Annotated[str | None, Field(alias="eventDescription")] = None
    event_start: Annotated[str | None, Field(alias="eventStart")] = None
    event_end: Annotated[str | None, Field(alias="eventEnd")] = None
    search_list_start: Annotated[str | None, Field(alias="searchListStart")] = None
    search_list_end: Annotated[str | None, Field(alias="searchListEnd")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None


class UserSecretActionType(str, Enum):
    get_secret = "getSecret"
    update_secret = "updateSecret"


class UserSecretManagementActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    input_expression: Annotated[str | None, Field(alias="inputExpression")] = None
    output_var_name: Annotated[str | None, Field(alias="outputVarName")] = None
    secret_name: Annotated[str | None, Field(alias="secretName")] = None
    user_secret_action_type: Annotated[
        UserSecretActionType | None, Field(alias="userSecretActionType")
    ] = None


class ActionType(str, Enum):
    start = "start"
    stop = "stop"
    list = "list"


class InteractApplicationActionData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    action_type: Annotated[ActionType | None, Field(alias="actionType")] = None
    action_payload: Annotated[str | None, Field(alias="actionPayload")] = None
    application_name: Annotated[str | None, Field(alias="applicationName")] = None
