# generated by datamodel-codegen:
#   filename:  script.schema.json
#   timestamp: 2026-04-30T03:27:48+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import common_schema, script_action_schema


class Input(RootModel[tuple[str, str, bool]]):
    root: Annotated[tuple[str, str, bool], Field(max_length=3, min_length=3)]


class Output(Input):
    pass


class ScriptMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    editor_status: Annotated[
        common_schema.EditorStatusEnum, Field(alias="editorStatus")
    ]


class ScriptActionRow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actions: list[script_action_schema.ScriptAction]
    action_row_index: Annotated[int, Field(alias="actionRowIndex")]
    row_id: Annotated[int, Field(alias="rowID")]
    selected: bool


class ScriptProps(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    target_system: Annotated[common_schema.SystemName, Field(alias="targetSystem")]
    width: float
    height: float
    script_mode: Annotated[common_schema.ScriptModePropEnum, Field(alias="scriptMode")]
    deployment_to_library: Annotated[bool, Field(alias="deploymentToLibrary")]
    script_reference: Annotated[
        dict[str, Any] | None,
        Field(
            alias="scriptReference",
            description="Embedded scriptReference props for nested scripts. TODO: tighten once ScriptReference shape is stable.",
        ),
    ] = None


class Script(BaseModel):
    """
    Top-level Script document as edited in script-studio and executed by ScriptEngine.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    script_name: Annotated[str, Field(alias="scriptName")]
    action_rows: Annotated[list[ScriptActionRow], Field(alias="actionRows")]
    props: ScriptProps
    dependencies: list[str]
    inputs: Annotated[
        list[Input], Field(description="Tuples of [name, type, required].")
    ]
    outputs: list[Output]
    script_meta: Annotated[ScriptMeta, Field(alias="scriptMeta")]
    id: str
    interface_version: Annotated[int, Field(alias="interfaceVersion")]
    last_loaded_timestamp: Annotated[
        float | None, Field(alias="lastLoadedTimestamp")
    ] = None
