# generated by datamodel-codegen:
#   filename:  script-action.schema.json
#   timestamp: 2026-10-07T04:41:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ActionName(str, Enum):
    """
    Discriminator for the ScriptAction subtype. Note: searchPatternStartAction / searchPatternContinueAction / searchPatternEndAction are deprecated — retained for loading legacy scripts; do not author new uses.
    """

    joint_action = "jointAction"
    click_action = "clickAction"
    mouse_scroll_action = "mouseScrollAction"
    declare_scene = "declareScene"
    conditional_statement = "conditionalStatement"
    shell_script = "shellScript"
    log_action = "logAction"
    sleep_statement = "sleepStatement"
    variable_assignment = "variableAssignment"
    time_action = "timeAction"
    random_variable = "randomVariable"
    script_reference = "scriptReference"
    drag_location_source = "dragLocationSource"
    drag_location_target = "dragLocationTarget"
    detect_object = "detectObject"
    keyboard_action = "keyboardAction"
    search_pattern_start_action = "searchPatternStartAction"
    search_pattern_continue_action = "searchPatternContinueAction"
    search_pattern_end_action = "searchPatternEndAction"
    randomizer_action = "randomizerAction"
    json_file_action = "jsonFileAction"
    exception_action = "exceptionAction"
    navigate_action = "navigateAction"
    image_to_text_action = "ImageToTextAction"
    image_to_text_action_1 = "imageToTextAction"
    scale = "scale"
    send_message_action = "sendMessageAction"
    code_block = "codeBlock"
    for_loop_action = "forLoopAction"
    configuration_action = "configurationAction"
    adb_configuration_action = "ADBConfigurationAction"
    color_compare_action = "colorCompareAction"
    return_statement = "returnStatement"
    image_transformation_action = "imageTransformationAction"
    count_to_threshold_action = "countToThresholdAction"
    file_io_action = "fileIOAction"
    mask_merge_action = "maskMergeAction"
    mouse_move_action = "mouseMoveAction"
    mouse_interaction_action = "mouseInteractionAction"
    user_prompt_action = "userPromptAction"
    calendar_action = "calendarAction"
    user_secret_management_action = "userSecretManagementAction"
    interact_application_action = "interactApplicationAction"


class AssetType(str, Enum):
    """
    Selects the loader: `image` => binary decoded with the platform's image library; `json`/`pointList` => `JSON.parse`; `text` => raw UTF-8.
    """

    image = "image"
    json = "json"
    point_list = "pointList"
    text = "text"


class ScriptActionAsset(BaseModel):
    """
    One persisted asset belonging to a ScriptAction. The flat `assets/` folder layout uses `filePath` to locate the file. `attributePath` is the dot-path within the action where the loaded value should be placed (numeric segments traverse arrays). `md5` is the hash of the file's bytes; populated when the asset is first registered (e.g. via `ScriptFlatAssetsUtils.addActionAsset`).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    file_path: Annotated[
        str,
        Field(
            alias="filePath",
            description="Path relative to the script root, e.g. `assets/{md5}-{actionName}-{actionGroup}-{specificFileName}.{ext}`.",
        ),
    ]
    attribute_path: Annotated[
        str,
        Field(
            alias="attributePath",
            description="Dot-path within the ScriptAction where the loaded value lives (e.g. `actionData.srcImg`, `actionData.positiveExamples.0.floatingObject.img`, `actionIcon.icon`, `actionIcon.grid.0.0.icon`).",
        ),
    ]
    asset_type: Annotated[
        AssetType,
        Field(
            alias="assetType",
            description="Selects the loader: `image` => binary decoded with the platform's image library; `json`/`pointList` => `JSON.parse`; `text` => raw UTF-8.",
        ),
    ]
    md5: Annotated[str, Field(description="Hex MD5 of the file's bytes.")]


class ScriptAction(BaseModel):
    """
    A single ScriptAction node as authored in script-studio and consumed by ScriptEngine. The shape of `actionData` is discriminated on `actionName`; per-subtype payloads are defined in script-action-data.schema.json.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    action_name: Annotated[
        ActionName,
        Field(
            alias="actionName",
            description="Discriminator for the ScriptAction subtype. Note: searchPatternStartAction / searchPatternContinueAction / searchPatternEndAction are deprecated — retained for loading legacy scripts; do not author new uses.",
        ),
    ]
    action_icon: Annotated[
        dict[str, Any] | str | None,
        Field(
            alias="actionIcon",
            description="UI-only: icon descriptor (one of imageIcon|symbolIcon|svgIcon|textIcon|customIcon|blankIcon|gridIcon). Image references are persisted as relative paths or null.",
        ),
    ] = None
    action_data: Annotated[
        dict[str, Any],
        Field(
            alias="actionData",
            description="Per-actionName payload. Structure is selected by the oneOf below using actionName as discriminator.",
        ),
    ]
    action_group: Annotated[int, Field(alias="actionGroup")]
    action_groups: Annotated[
        list[int] | None,
        Field(alias="actionGroups", description="Only used by jointAction."),
    ] = None
    action_version: Annotated[int, Field(alias="actionVersion")]
    action_version_code: Annotated[str, Field(alias="actionVersionCode")]
    action_label: Annotated[str, Field(alias="actionLabel")]
    action_row_row_index: Annotated[int, Field(alias="actionRowRowIndex")]
    action_row_action_index: Annotated[int, Field(alias="actionRowActionIndex")]
    visualizer_row_index: Annotated[int, Field(alias="visualizerRowIndex")]
    visualizer_action_index: Annotated[int, Field(alias="visualizerActionIndex")]
    visualizer_x: Annotated[float, Field(alias="visualizerX")]
    visualizer_y: Annotated[float, Field(alias="visualizerY")]
    child_groups: Annotated[
        list[dict[str, Any]],
        Field(
            alias="childGroups",
            description="ActionLink array; concrete shape varies by branchingBehavior.",
        ),
    ]
    parent_groups: Annotated[list[int], Field(alias="parentGroups")]
    displayables: list[dict[str, Any]]
    configurables: list[dict[str, Any]]
    linking_behaviors: Annotated[list[dict[str, Any]], Field(alias="linkingBehaviors")]
    action_assets: Annotated[
        list[ScriptActionAsset] | None,
        Field(
            alias="actionAssets",
            description="Per-action registry of files persisted under `assets/` (flat layout, since interfaceVersion 21). Each entry locates a file and the dot-path on the action where the loaded value should be placed at deserialise time.",
        ),
    ] = None
    selected: bool | None = None
    draggable: bool | None = None
    highlight: str | None = None
    help_tip_expanded: Annotated[bool | None, Field(alias="helpTipExpanded")] = None
